# Generated by Django 4.2.7 on 2023-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internNumber', models.PositiveIntegerField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('graduateCourse', models.CharField(max_length=50)),
                ('startContract', models.DateField()),
                ('endContract', models.DateField()),
            ],
        ),
    ]
